"""HTML forensic report generation."""

import sqlite3
from .pages import read_database_header
from .schema import get_schema, get_foreign_keys
from .check import run_integrity_check


def generate_forensic_report(database: str, output_path: str, title: str = "SQLite Forensic Report") -> str:
    """Generate a standalone HTML forensic report."""
    hdr = read_database_header(database)
    schema_objects = get_schema(database)
    fk_list = get_foreign_keys(database)
    integrity = run_integrity_check(database)

    conn = sqlite3.connect(database)
    page_count = conn.execute("PRAGMA page_count").fetchone()[0]
    freelist = conn.execute("PRAGMA freelist_count").fetchone()[0]
    conn.close()

    # Build tables HTML
    tables_html = ""
    tables = [o for o in schema_objects if o["type"] == "table"]
    for t in tables:
        cols = t.get("columns", [])
        col_rows = ""
        for c in cols:
            pk = "🔑" if c["pk"] else ""
            nn = " NOT NULL" if c["notnull"] else ""
            dflt = f" DEFAULT {c['default']}" if c["default"] is not None else ""
            col_rows += f"""<tr><td>{pk} {c['name']}</td><td>{c['type']}{nn}{dflt}</td></tr>\n"""
        tables_html += f"""
        <div class="card">
            <div class="card-header">{t['name']}</div>
            <div class="card-body">
                <table class="table">
                    <thead><tr><th>Column</th><th>Type</th></tr></thead>
                    <tbody>{col_rows}</tbody>
                </table>
            </div>
        </div>"""

    # Status
    status_color = "green" if integrity.get("passed") else "red"
    status_text = "PASSED" if integrity.get("passed") else "FAILED"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }}
h1 {{ font-size: 2rem; margin-bottom: 0.5rem; }}
h2 {{ font-size: 1.4rem; margin: 1.5rem 0 0.5rem; color: #93c5fd; }}
.meta {{ color: #94a3b8; margin-bottom: 1.5rem; }}
.grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
.stat {{ background: #1e293b; padding: 1.2rem; border-radius: 0.75rem; }}
.stat-value {{ font-size: 1.8rem; font-weight: 700; }}
.stat-label {{ font-size: 0.85rem; color: #94a3b8; margin-top: 0.25rem; }}
.stat.green {{ border-left: 4px solid #22c55e; }}
.stat.yellow {{ border-left: 4px solid #eab308; }}
.stat.red {{ border-left: 4px solid #ef4444; }}
.card {{ background: #1e293b; border-radius: 0.75rem; margin-bottom: 1rem; overflow: hidden; }}
.card-header {{ background: #334155; padding: 0.75rem 1rem; font-weight: 600; font-size: 1.1rem; }}
.card-body {{ padding: 1rem; }}
.table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
.table th {{ text-align: left; padding: 0.5rem; background: #1e293b; border-bottom: 2px solid #334155; }}
.table td {{ padding: 0.5rem; border-bottom: 1px solid #334155; font-family: monospace; }}
.foreign-keys {{ margin-top: 1rem; }}
.fk-item {{ padding: 0.5rem; background: #0f172a; border-radius: 0.5rem; margin-bottom: 0.5rem; font-size: 0.9rem; }}
.schema-sql {{ background: #0f172a; padding: 1rem; border-radius: 0.5rem; font-family: monospace; font-size: 0.85rem; overflow-x: auto; white-space: pre; margin-top: 0.5rem; }}
a {{ color: #60a5fa; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="meta">Database: {database} &middot; Generated by SQLime</p>

<div class="grid">
    <div class="stat green">
        <div class="stat-value">{integrity.get('passed', False) and 'PASSED' or 'FAILED'}</div>
        <div class="stat-label">Integrity Check</div>
    </div>
    <div class="stat">
        <div class="stat-value">{hdr.db_size_pages}</div>
        <div class="stat-label">Total Pages</div>
    </div>
    <div class="stat">
        <div class="stat-value">{page_count}</div>
        <div class="stat-label">Allocated Pages</div>
    </div>
    <div class="stat">
        <div class="stat-value">{freelist}</div>
        <div class="stat-label">Free Pages</div>
    </div>
    <div class="stat">
        <div class="stat-value">{(hdr.db_size_pages * hdr.page_size) / 1024:.1f}</div>
        <div class="stat-label">Size (KB)</div>
    </div>
    <div class="stat">
        <div class="stat-value">{len(tables)}</div>
        <div class="stat-label">Tables</div>
    </div>
</div>

<h2>Database Header</h2>
<div class="card">
    <div class="card-body">
        <table class="table">
            <tr><td>Page Size</td><td>{hdr.page_size} bytes</td></tr>
            <tr><td>Encoding</td><td>{hdr.encoding_name()}</td></tr>
            <tr><td>Schema Format</td><td>{hdr.schema_format}</td></tr>
            <tr><td>Application ID</td><td>0x{hdr.application_id:08X}</td></tr>
            <tr><td>User Version</td><td>{hdr.user_version}</td></tr>
            <tr><td>File Change Counter</td><td>{hdr.file_change_counter}</td></tr>
        </table>
    </div>
</div>

<h2>Schema ({len(tables)} tables)</h2>
{tables_html}

<h2>Foreign Keys ({len(fk_list)} relations)</h2>
<div class="card">
    <div class="card-body">
    {''.join(
        f'<div class="fk-item">{fk["table"]}.{fk["from"]} → {fk["references"]}.{fk["to"]}</div>'
        for fk in fk_list
    ) if fk_list else '<p>None</p>'}
    </div>
</div>

<h2>Integrity Check</h2>
<div class="card">
    <div class="card-body">
        <p>Status: <strong style="color:{status_color}">{status_text}</strong></p>
        {''.join(f'<p style="color:#f87171">- {err}</p>' for err in integrity.get('errors', []))}
    </div>
</div>

<p style="margin-top:2rem;color:#64748b;font-size:0.8rem;">Generated by SQLime — SQLite Forensic Toolkit</p>
</body>
</html>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    return output_path
